0.8HTTPRequest/Models/ErrorViewModel.cs
using System;

namespace _0._8HTTPRequest.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

0.8HTTPRequest/Models/test1.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace _0._8HTTPRequest.Models
{
    public class test1
    {
        public int id { get; set; }
        public string Groceria { get; set; }
    }
}

0.8HTTPRequest/Models/test2.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace _0._8HTTPRequest.Models
{
    public class test2
    {
        public Standard standard { get; set; }
        public string longt { get; set; }
        public Alt alt { get; set; }
        public Elevation elevation { get; set; }
        public string latt { get; set; }
    }
    public class Addresst
    {
    }

    public class Postal
    {
    }

    public class Standard
    {
        public Addresst addresst { get; set; }
        public string city { get; set; }
        public string prov { get; set; }
        public string countryname { get; set; }
        public Postal postal { get; set; }
        public string confidence { get; set; }
    }

    public class Region
    {
    }

    public class Loc
    {
        public string longt { get; set; }
        public string prov { get; set; }
        public string city { get; set; }
        public string countryname { get; set; }
        public string postal { get; set; }
        public Region region { get; set; }
        public string latt { get; set; }
    }

    public class Alt
    {
        public Loc loc { get; set; }
    }

    public class Elevation
    {
    }

   

}

0.8HTTPRequest/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using _0._8HTTPRequest.Models;

namespace _0._8HTTPRequest.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

0.8HTTPRequest/Controllers/Test1APIController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _0._8HTTPRequest.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace _0._8HTTPRequest.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class Test1APIController : ControllerBase
    {
        [HttpGet]
        public  List<test1> GetAll()
        {
            List<test1> lista = new List<test1>();

            lista.Add(new test1()
            {
                id = 1,
                Groceria = "Marico"
            });

            lista.Add(new test1()
            {
                id = 2,
                Groceria = "Parchita"
            });

            lista.Add(new test1()
            {
                id = 3,
                Groceria = "Rosca Dulce"
            });

            return lista;

        }

        [HttpGet("{id}")]
        public test1 GetID(int id)
        {
            return new test1()
            {
                id = id,
                Groceria = "Marico no hay cambio solo es un test"
            };
        }

        [HttpPost]
        public bool Post([FromBody]test1 insert)
        {
            if (insert != null)
                return true;
            return false;

        }


    }
}

0.8HTTPRequest/Controllers/Test1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Net;
using System.IO;
using _0._8HTTPRequest.Models;
using _0._8HTTPRequest.helpers;
using Newtonsoft.Json;

namespace _0._8HTTPRequest.Controllers
{
    public class Test1Controller : Controller
    {
        private readonly string ControladorAPI = "https://localhost:44306/api/test1api";
        public IActionResult Index()
        {
            string json = HttpSolicitudes.GetHTTP(ControladorAPI);
            List<test1> Lista = new List<test1>();
            Lista = JsonConvert.DeserializeObject<List<test1>>(json);
            return View(Lista);
        }

        public IActionResult Nuevo()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Nuevo(test1 insert)
        {
            try
            {
                string json = JsonConvert.SerializeObject(insert);
                var respuesta = HttpSolicitudes.PostHTTP<test1>(ControladorAPI, json);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(insert);
            }


        }

    }
}

0.8HTTPRequest/Controllers/test2Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _0._8HTTPRequest.helpers;
using _0._8HTTPRequest.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace _0._8HTTPRequest.Controllers
{
    public class test2Controller : Controller
    {
        public IActionResult Index()
        {
            test2 datos1 = new test2();
            string url = "https://geocode.xyz/Hauptstr.,+57632+Caracas?json=1";
            string respuesta = HttpSolicitudes.GetHTTP(url);
            datos1 = JsonConvert.DeserializeObject<test2>(respuesta);

            return View(datos1);
        }
      

    }
}

0.8HTTPRequest/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

0.8HTTPRequest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - _0._8HTTPRequest</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">_0._8HTTPRequest</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="test1" asp-action="index">test1</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="test2" asp-action="index">test2</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - _0._8HTTPRequest - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/jquery-3.5.1.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

0.8HTTPRequest/Views/Test1/Index.cshtml
@model IEnumerable<_0._8HTTPRequest.Models.test1>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a class="btn btn-dark" asp-action="Nuevo" asp-controller="test1">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Groceria)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Groceria)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

0.8HTTPRequest/Views/Test1/Nuevo.cshtml
@using _0._8HTTPRequest.Models;
@model test1

@{
    ViewData["Title"] = "Nuevo";
}

<h1>Agregar Nuevo Elemento</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Nuevo" asp-controller="test1" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="id" class="control-label"></label>
                <input asp-for="id" readonly value="0" class="form-control" />
                <span asp-validation-for="id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Groceria" class="control-label"></label>
                <input asp-for="Groceria" class="form-control" />
                <span asp-validation-for="Groceria" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-dark" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-danger" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

0.8HTTPRequest/Views/test2/FailIndex.cshtml
@using _0._8HTTPRequest.Models;
@model test2

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>


<div>
    <label for="ciudad">Ingrese Ciudad</label>
    <input id="ciudad" type="text" />
    <button id="btn" class="btn btn-dark">Ver °.°!</button>

</div>

<section class="datosApi1">

 
        <label for="latt">Latitud</label>
        <input id="latt" type="text" />
        <label for="longt">Longitud</label>
        <input id="longt" type="text"  />

     
</section>



<script>
    const btn = document.getElementById("btn");
    const ciudad = document.getElementById("ciudad");
    btn.addEventListener('click', () => {
        $.get("Index/?ciudad=" + ciudad.value, function(data) {

            document.getElementById("latt").value = data.latt;
            document.getElementById("longt").value = data.longt;
        });
    });


</script>

0.8HTTPRequest/Views/test2/Index.cshtml
@model _0._8HTTPRequest.Models.test2

@{
    ViewData["Title"] = "Index";
}



<section>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.longt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.longt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.latt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.latt)
        </dd>
    </dl>
</section>